# My version with some minor tweaks
version: '3.7'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:8000
# # Original from TDD guide
# version: '3.7'

# services:
#   web:
#     build: ./src
#     command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
#     volumes:
#       - ./src/:/usr/src/app/
#     ports:
#       - 8002:8000
